/* Generated by scripts/tools: host-memory stub for the h3_gpu API.
 * Compiled only on platforms without a real GPU backend (Linux).
 * Every operation fails cleanly; h3_gpu_create() reports that no
 * backend (Metal/Vulkan/CUDA) is available in this build. */
#include "h3_gpu.h"

#include <stdio.h>
#include <string.h>

struct h3_gpu {
    char error[512];
};

struct h3_gpu_tensor {
    size_t elements;
    h3_gpu_dtype dtype;
};

static const char *h3_gpu_stub_message(void) {
    return "no GPU backend in this build (Metal is macOS-only; Vulkan/CUDA scaffolding pending)";
}

h3_gpu * h3_gpu_create(const char *shader_source_path,
                      char *error, size_t error_size) {
    (void)shader_source_path;
    if (error && error_size) snprintf(error, error_size, "%s", h3_gpu_stub_message());
    return NULL;
}

void h3_gpu_free(h3_gpu *gpu) {
(void)gpu;
}

int h3_gpu_is_m5(const h3_gpu *gpu) {
(void)gpu;
    return 0;
}

int h3_gpu_has_nax_mlp(const h3_gpu *gpu) {
(void)gpu;
    return 0;
}

int h3_gpu_has_int8_mlp(const h3_gpu *gpu) {
(void)gpu;
    return 0;
}

h3_gpu_tensor * h3_gpu_tensor_new_f32(h3_gpu *gpu, size_t elements) {
(void)gpu; (void)elements;
    return NULL;
}

h3_gpu_tensor * h3_gpu_tensor_new_bf16(h3_gpu *gpu, size_t elements) {
(void)gpu; (void)elements;
    return NULL;
}

h3_gpu_tensor * h3_gpu_tensor_new_i8(h3_gpu *gpu, size_t elements) {
(void)gpu; (void)elements;
    return NULL;
}

h3_gpu_tensor * h3_gpu_tensor_from_f32(h3_gpu *gpu, const float *values,
                                      size_t elements) {
(void)gpu; (void)values; (void)elements;
    return NULL;
}

h3_gpu_tensor * h3_gpu_tensor_from_bf16(h3_gpu *gpu, const uint16_t *values,
                                       size_t elements) {
(void)gpu; (void)values; (void)elements;
    return NULL;
}

h3_gpu_tensor * h3_gpu_tensor_from_u32(h3_gpu *gpu, const uint32_t *values,
                                      size_t elements) {
(void)gpu; (void)values; (void)elements;
    return NULL;
}

h3_gpu_tensor * h3_gpu_tensor_load_bf16(h3_gpu *gpu, const char *path,
                                       uint64_t file_offset, size_t elements) {
(void)gpu; (void)path; (void)file_offset; (void)elements;
    return NULL;
}

h3_gpu_tensor * h3_gpu_tensor_load_f32(h3_gpu *gpu, const char *path,
                                      uint64_t file_offset, size_t elements) {
(void)gpu; (void)path; (void)file_offset; (void)elements;
    return NULL;
}

int h3_gpu_tensor_read_file_bf16(h3_gpu_tensor *tensor, const char *path,
                                 uint64_t file_offset, size_t elements,
                                 char *error, size_t error_size) {
(void)tensor; (void)path; (void)file_offset; (void)elements; (void)error; (void)error_size;
    return -1;
}

int h3_gpu_tensor_stream_file_bf16(h3_gpu_tensor *tensor, const char *path,
                                   uint64_t file_offset, size_t elements,
                                   char *error, size_t error_size) {
(void)tensor; (void)path; (void)file_offset; (void)elements; (void)error; (void)error_size;
    return -1;
}

void h3_gpu_tensor_free(h3_gpu_tensor *tensor) {
(void)tensor;
}

size_t h3_gpu_tensor_elements(const h3_gpu_tensor *tensor) {
(void)tensor;
    return 0;
}

h3_gpu_dtype h3_gpu_tensor_dtype(const h3_gpu_tensor *tensor) {
(void)tensor;
    return H3_GPU_F32;
}

int h3_gpu_tensor_read_f32(const h3_gpu_tensor *tensor, float *values,
                           size_t elements) {
(void)tensor; (void)values; (void)elements;
    return -1;
}

int h3_gpu_tensor_read_f32_range(const h3_gpu_tensor *tensor,
                                 size_t source_offset, float *values,
                                 size_t elements) {
(void)tensor; (void)source_offset; (void)values; (void)elements;
    return -1;
}

int h3_gpu_tensor_read_bf16(const h3_gpu_tensor *tensor, uint16_t *values,
                            size_t elements) {
(void)tensor; (void)values; (void)elements;
    return -1;
}

int h3_gpu_tensor_write_f32(h3_gpu_tensor *tensor, const float *values,
                            size_t elements) {
(void)tensor; (void)values; (void)elements;
    return -1;
}

int h3_gpu_tensor_write_f32_range(h3_gpu_tensor *tensor,
                                  size_t destination_offset,
                                  const float *values, size_t elements) {
(void)tensor; (void)destination_offset; (void)values; (void)elements;
    return -1;
}

int h3_gpu_tensor_write_bf16(h3_gpu_tensor *tensor, const uint16_t *values,
                             size_t elements) {
(void)tensor; (void)values; (void)elements;
    return -1;
}

int h3_gpu_tensor_write_bf16_range(h3_gpu_tensor *tensor,
                                   size_t destination_offset,
                                   const uint16_t *values, size_t elements) {
(void)tensor; (void)destination_offset; (void)values; (void)elements;
    return -1;
}

int h3_gpu_begin(h3_gpu *gpu) {
(void)gpu;
    return -1;
}

int h3_gpu_continue(h3_gpu *gpu) {
(void)gpu;
    return -1;
}

int h3_gpu_submit(h3_gpu *gpu) {
(void)gpu;
    return -1;
}

const char * h3_gpu_error(const h3_gpu *gpu) {
    (void)gpu;
    return h3_gpu_stub_message();
}

int h3_gpu_get_stats(const h3_gpu *gpu, h3_gpu_stats *stats) {
(void)gpu; (void)stats;
    return -1;
}

void h3_gpu_profile_set_label(h3_gpu *gpu, const char *label) {
(void)gpu; (void)label;
}

void h3_gpu_profile_mark(h3_gpu *gpu, const char *phase) {
(void)gpu; (void)phase;
}

int h3_gpu_linear_f32(h3_gpu *gpu, h3_gpu_tensor *output,
                      const h3_gpu_tensor *input, const h3_gpu_tensor *weight,
                      const h3_gpu_tensor *bias, uint32_t rows,
                      uint32_t input_dim, uint32_t output_dim) {
(void)gpu; (void)output; (void)input; (void)weight; (void)bias; (void)rows; (void)input_dim; (void)output_dim;
    return -1;
}

int h3_gpu_patch_linear_bf16(h3_gpu *gpu, h3_gpu_tensor *output,
                             const h3_gpu_tensor *input,
                             const h3_gpu_tensor *weight,
                             const h3_gpu_tensor *bias, uint32_t rows,
                             uint32_t input_dim, uint32_t output_dim) {
(void)gpu; (void)output; (void)input; (void)weight; (void)bias; (void)rows; (void)input_dim; (void)output_dim;
    return -1;
}

int h3_gpu_patch_linear_bf16_offset(
                             h3_gpu *gpu, h3_gpu_tensor *output,
                             size_t output_offset,
                             const h3_gpu_tensor *input, size_t input_offset,
                             const h3_gpu_tensor *weight,
                             const h3_gpu_tensor *bias, uint32_t rows,
                             uint32_t input_dim, uint32_t output_dim) {
(void)gpu; (void)output; (void)output_offset; (void)input; (void)input_offset; (void)weight; (void)bias; (void)rows; (void)input_dim; (void)output_dim;
    return -1;
}

int h3_gpu_patch_linear_bf16_map(
                             h3_gpu *gpu, h3_gpu_tensor *output,
                             const h3_gpu_tensor *input,
                             const h3_gpu_tensor *weight,
                             const h3_gpu_tensor *bias,
                             const h3_gpu_tensor *row_map,
                             uint32_t output_rows, uint32_t rows,
                             uint32_t input_dim, uint32_t output_dim) {
(void)gpu; (void)output; (void)input; (void)weight; (void)bias; (void)row_map; (void)output_rows; (void)rows; (void)input_dim; (void)output_dim;
    return -1;
}

int h3_gpu_silu_f32(h3_gpu *gpu, h3_gpu_tensor *output,
                    const h3_gpu_tensor *input, uint32_t elements) {
(void)gpu; (void)output; (void)input; (void)elements;
    return -1;
}

int h3_gpu_cast_f32_to_bf16(h3_gpu *gpu, h3_gpu_tensor *output,
                            const h3_gpu_tensor *input, uint32_t elements) {
(void)gpu; (void)output; (void)input; (void)elements;
    return -1;
}

int h3_gpu_cast_bf16_to_f32(h3_gpu *gpu, h3_gpu_tensor *output,
                            const h3_gpu_tensor *input, uint32_t elements) {
(void)gpu; (void)output; (void)input; (void)elements;
    return -1;
}

int h3_gpu_copy_bf16(h3_gpu *gpu, h3_gpu_tensor *destination,
                     size_t destination_offset,
                     const h3_gpu_tensor *source, size_t source_offset,
                     size_t elements) {
(void)gpu; (void)destination; (void)destination_offset; (void)source; (void)source_offset; (void)elements;
    return -1;
}

int h3_gpu_copy_f32(h3_gpu *gpu, h3_gpu_tensor *destination,
                    size_t destination_offset,
                    const h3_gpu_tensor *source, size_t source_offset,
                    size_t elements) {
(void)gpu; (void)destination; (void)destination_offset; (void)source; (void)source_offset; (void)elements;
    return -1;
}

int h3_gpu_rms_norm_f32(h3_gpu *gpu, h3_gpu_tensor *output,
                        const h3_gpu_tensor *input,
                        const h3_gpu_tensor *weight, uint32_t rows,
                        uint32_t width, float epsilon) {
(void)gpu; (void)output; (void)input; (void)weight; (void)rows; (void)width; (void)epsilon;
    return -1;
}

int h3_gpu_adaln_f32(h3_gpu *gpu, h3_gpu_tensor *output,
                     const h3_gpu_tensor *input,
                     const h3_gpu_tensor *norm_weight,
                     const h3_gpu_tensor *modulation,
                     const h3_gpu_tensor *row_map, uint32_t rows,
                     uint32_t width, uint32_t slots, uint32_t shift_slot,
                     uint32_t scale_slot, float epsilon) {
(void)gpu; (void)output; (void)input; (void)norm_weight; (void)modulation; (void)row_map; (void)rows; (void)width; (void)slots; (void)shift_slot; (void)scale_slot; (void)epsilon;
    return -1;
}

int h3_gpu_gate_f32(h3_gpu *gpu, h3_gpu_tensor *output,
                    const h3_gpu_tensor *residual,
                    const h3_gpu_tensor *branch,
                    const h3_gpu_tensor *modulation,
                    const h3_gpu_tensor *row_map, uint32_t rows,
                    uint32_t width, uint32_t slots, uint32_t gate_slot) {
(void)gpu; (void)output; (void)residual; (void)branch; (void)modulation; (void)row_map; (void)rows; (void)width; (void)slots; (void)gate_slot;
    return -1;
}

int h3_gpu_qkv_rope_f32(h3_gpu *gpu, h3_gpu_tensor *query,
                        h3_gpu_tensor *key, h3_gpu_tensor *value,
                        const h3_gpu_tensor *qkv,
                        const h3_gpu_tensor *q_norm,
                        const h3_gpu_tensor *k_norm,
                        const h3_gpu_tensor *rope_cos,
                        const h3_gpu_tensor *rope_sin, uint32_t sequence,
                        uint32_t heads, uint32_t head_dim,
                        uint32_t rope_half, float epsilon) {
(void)gpu; (void)query; (void)key; (void)value; (void)qkv; (void)q_norm; (void)k_norm; (void)rope_cos; (void)rope_sin; (void)sequence; (void)heads; (void)head_dim; (void)rope_half; (void)epsilon;
    return -1;
}

int h3_gpu_sdpa_f32(h3_gpu *gpu, h3_gpu_tensor *output,
                    const h3_gpu_tensor *query, const h3_gpu_tensor *key,
                    const h3_gpu_tensor *value, uint32_t sequence,
                    uint32_t heads, uint32_t head_dim, float scale) {
(void)gpu; (void)output; (void)query; (void)key; (void)value; (void)sequence; (void)heads; (void)head_dim; (void)scale;
    return -1;
}

int h3_gpu_swiglu_f32(h3_gpu *gpu, h3_gpu_tensor *output,
                      const h3_gpu_tensor *fused, uint32_t rows,
                      uint32_t width) {
(void)gpu; (void)output; (void)fused; (void)rows; (void)width;
    return -1;
}

int h3_gpu_scale_add_f32(h3_gpu *gpu, h3_gpu_tensor *output,
                         const h3_gpu_tensor *residual,
                         const h3_gpu_tensor *branch,
                         const h3_gpu_tensor *scale, uint32_t rows,
                         uint32_t width) {
(void)gpu; (void)output; (void)residual; (void)branch; (void)scale; (void)rows; (void)width;
    return -1;
}

int h3_gpu_layer_norm_f32(h3_gpu *gpu, h3_gpu_tensor *output,
                          const h3_gpu_tensor *input,
                          const h3_gpu_tensor *weight,
                          const h3_gpu_tensor *bias, uint32_t rows,
                          uint32_t width, float epsilon) {
(void)gpu; (void)output; (void)input; (void)weight; (void)bias; (void)rows; (void)width; (void)epsilon;
    return -1;
}

int h3_gpu_video_qkv_rope_f32(h3_gpu *gpu, h3_gpu_tensor *query,
                              h3_gpu_tensor *key, h3_gpu_tensor *value,
                              const h3_gpu_tensor *qkv,
                              const h3_gpu_tensor *rope_cos,
                              const h3_gpu_tensor *rope_sin,
                              uint32_t sequence, uint32_t heads,
                              uint32_t head_dim, uint32_t rope_half,
                              float epsilon) {
(void)gpu; (void)query; (void)key; (void)value; (void)qkv; (void)rope_cos; (void)rope_sin; (void)sequence; (void)heads; (void)head_dim; (void)rope_half; (void)epsilon;
    return -1;
}

int h3_gpu_conv1d_f32(h3_gpu *gpu, h3_gpu_tensor *output,
                      const h3_gpu_tensor *input,
                      const h3_gpu_tensor *weight,
                      const h3_gpu_tensor *bias, uint32_t batch,
                      uint32_t length, uint32_t input_channels,
                      uint32_t output_channels, uint32_t kernel,
                      uint32_t padding, uint32_t dilation) {
(void)gpu; (void)output; (void)input; (void)weight; (void)bias; (void)batch; (void)length; (void)input_channels; (void)output_channels; (void)kernel; (void)padding; (void)dilation;
    return -1;
}

int h3_gpu_conv1d_stride_f32(h3_gpu *gpu, h3_gpu_tensor *output,
                      const h3_gpu_tensor *input,
                      const h3_gpu_tensor *weight,
                      const h3_gpu_tensor *bias, uint32_t batch,
                      uint32_t length, uint32_t input_channels,
                      uint32_t output_channels, uint32_t kernel,
                      uint32_t stride, uint32_t padding,
                      uint32_t dilation) {
(void)gpu; (void)output; (void)input; (void)weight; (void)bias; (void)batch; (void)length; (void)input_channels; (void)output_channels; (void)kernel; (void)stride; (void)padding; (void)dilation;
    return -1;
}

int h3_gpu_conv_transpose1d_f32(
                      h3_gpu *gpu, h3_gpu_tensor *output,
                      const h3_gpu_tensor *input,
                      const h3_gpu_tensor *weight,
                      const h3_gpu_tensor *bias, uint32_t batch,
                      uint32_t length, uint32_t input_channels,
                      uint32_t output_channels, uint32_t kernel,
                      uint32_t stride, uint32_t padding) {
(void)gpu; (void)output; (void)input; (void)weight; (void)bias; (void)batch; (void)length; (void)input_channels; (void)output_channels; (void)kernel; (void)stride; (void)padding;
    return -1;
}

int h3_gpu_weight_norm_f32(h3_gpu *gpu, h3_gpu_tensor *output,
                           const h3_gpu_tensor *vector,
                           const h3_gpu_tensor *magnitude,
                           uint32_t outer, uint32_t inner) {
(void)gpu; (void)output; (void)vector; (void)magnitude; (void)outer; (void)inner;
    return -1;
}

int h3_gpu_add_scaled_f32(h3_gpu *gpu, h3_gpu_tensor *output,
                          const h3_gpu_tensor *left,
                          const h3_gpu_tensor *right, float left_scale,
                          float right_scale, uint32_t elements) {
(void)gpu; (void)output; (void)left; (void)right; (void)left_scale; (void)right_scale; (void)elements;
    return -1;
}

int h3_gpu_alias_free_snake_f32(
                          h3_gpu *gpu, h3_gpu_tensor *output,
                          const h3_gpu_tensor *input,
                          const h3_gpu_tensor *alpha_log,
                          const h3_gpu_tensor *beta_log,
                          const h3_gpu_tensor *upsample_filter,
                          const h3_gpu_tensor *downsample_filter,
                          uint32_t batch, uint32_t length,
                          uint32_t channels) {
(void)gpu; (void)output; (void)input; (void)alpha_log; (void)beta_log; (void)upsample_filter; (void)downsample_filter; (void)batch; (void)length; (void)channels;
    return -1;
}

int h3_gpu_snake1d_f32(h3_gpu *gpu, h3_gpu_tensor *output,
                       const h3_gpu_tensor *input,
                       const h3_gpu_tensor *alpha, uint32_t batch,
                       uint32_t length, uint32_t channels) {
(void)gpu; (void)output; (void)input; (void)alpha; (void)batch; (void)length; (void)channels;
    return -1;
}

int h3_gpu_audio_qkv_split_f32(h3_gpu *gpu,
                       h3_gpu_tensor *query, h3_gpu_tensor *key,
                       h3_gpu_tensor *value, const h3_gpu_tensor *qkv,
                       const h3_gpu_tensor *q_bias,
                       const h3_gpu_tensor *k_bias,
                       const h3_gpu_tensor *v_bias, uint32_t batch,
                       uint32_t length, uint32_t heads,
                       uint32_t head_dim) {
(void)gpu; (void)query; (void)key; (void)value; (void)qkv; (void)q_bias; (void)k_bias; (void)v_bias; (void)batch; (void)length; (void)heads; (void)head_dim;
    return -1;
}

int h3_gpu_sdpa_causal_f32(h3_gpu *gpu, h3_gpu_tensor *output,
                       const h3_gpu_tensor *query,
                       const h3_gpu_tensor *key,
                       const h3_gpu_tensor *value, uint32_t batch,
                       uint32_t sequence, uint32_t heads,
                       uint32_t head_dim, float scale) {
(void)gpu; (void)output; (void)query; (void)key; (void)value; (void)batch; (void)sequence; (void)heads; (void)head_dim; (void)scale;
    return -1;
}

int h3_gpu_audio_attention_pool_f32(h3_gpu *gpu,
                       h3_gpu_tensor *output,
                       const h3_gpu_tensor *attended, uint32_t batch,
                       uint32_t length, uint32_t heads,
                       uint32_t head_dim, uint32_t output_dim) {
(void)gpu; (void)output; (void)attended; (void)batch; (void)length; (void)heads; (void)head_dim; (void)output_dim;
    return -1;
}

int h3_gpu_geglu_f32(h3_gpu *gpu, h3_gpu_tensor *output,
                     const h3_gpu_tensor *gate,
                     const h3_gpu_tensor *linear, uint32_t elements) {
(void)gpu; (void)output; (void)gate; (void)linear; (void)elements;
    return -1;
}

int h3_gpu_clip_f32(h3_gpu *gpu, h3_gpu_tensor *output,
                    const h3_gpu_tensor *input, uint32_t elements,
                    float minimum, float maximum) {
(void)gpu; (void)output; (void)input; (void)elements; (void)minimum; (void)maximum;
    return -1;
}

int h3_gpu_vae_encoder_pad_f32(
                    h3_gpu *gpu, h3_gpu_tensor *output,
                    const h3_gpu_tensor *input, uint32_t batch,
                    uint32_t depth, uint32_t height, uint32_t width,
                    uint32_t channels, uint32_t depth_front,
                    uint32_t height_before, uint32_t height_after,
                    uint32_t width_before, uint32_t width_after) {
(void)gpu; (void)output; (void)input; (void)batch; (void)depth; (void)height; (void)width; (void)channels; (void)depth_front; (void)height_before; (void)height_after; (void)width_before; (void)width_after;
    return -1;
}

int h3_gpu_conv3d_f32(h3_gpu *gpu, h3_gpu_tensor *output,
                      const h3_gpu_tensor *input,
                      const h3_gpu_tensor *weight,
                      const h3_gpu_tensor *bias, uint32_t batch,
                      uint32_t depth, uint32_t height, uint32_t width,
                      uint32_t input_channels, uint32_t output_channels,
                      uint32_t kernel_depth, uint32_t kernel_height,
                      uint32_t kernel_width, uint32_t stride_depth,
                      uint32_t stride_height, uint32_t stride_width) {
(void)gpu; (void)output; (void)input; (void)weight; (void)bias; (void)batch; (void)depth; (void)height; (void)width; (void)input_channels; (void)output_channels; (void)kernel_depth; (void)kernel_height; (void)kernel_width; (void)stride_depth; (void)stride_height; (void)stride_width;
    return -1;
}

int h3_gpu_vae_encoder_group_norm_silu_f32(
                      h3_gpu *gpu, h3_gpu_tensor *output,
                      const h3_gpu_tensor *input,
                      const h3_gpu_tensor *weight,
                      const h3_gpu_tensor *bias, uint32_t batch,
                      uint32_t depth, uint32_t height, uint32_t width,
                      uint32_t channels, uint32_t groups, float epsilon) {
(void)gpu; (void)output; (void)input; (void)weight; (void)bias; (void)batch; (void)depth; (void)height; (void)width; (void)channels; (void)groups; (void)epsilon;
    return -1;
}

int h3_gpu_linear_bf16(h3_gpu *gpu, h3_gpu_tensor *output,
                       const h3_gpu_tensor *input,
                       const h3_gpu_tensor *weight,
                       const h3_gpu_tensor *bias, uint32_t rows,
                       uint32_t input_dim, uint32_t output_dim) {
(void)gpu; (void)output; (void)input; (void)weight; (void)bias; (void)rows; (void)input_dim; (void)output_dim;
    return -1;
}

int h3_gpu_mlp_bf16(h3_gpu *gpu, h3_gpu_tensor *output,
                    const h3_gpu_tensor *input,
                    const h3_gpu_tensor *fc1_weight,
                    const h3_gpu_tensor *fc2_weight, uint32_t rows,
                    uint32_t input_dim, uint32_t hidden_dim,
                    uint32_t output_dim) {
(void)gpu; (void)output; (void)input; (void)fc1_weight; (void)fc2_weight; (void)rows; (void)input_dim; (void)hidden_dim; (void)output_dim;
    return -1;
}

int h3_gpu_mlp_nax_bf16(h3_gpu *gpu, h3_gpu_tensor *output,
                        h3_gpu_tensor *activated,
                        const h3_gpu_tensor *input,
                        const h3_gpu_tensor *fc1_weight,
                        const h3_gpu_tensor *fc2_weight, uint32_t rows,
                        uint32_t input_dim, uint32_t hidden_dim,
                        uint32_t output_dim) {
(void)gpu; (void)output; (void)activated; (void)input; (void)fc1_weight; (void)fc2_weight; (void)rows; (void)input_dim; (void)hidden_dim; (void)output_dim;
    return -1;
}

int h3_gpu_quantize_weight_int8(h3_gpu *gpu, h3_gpu_tensor *output,
                                h3_gpu_tensor *scales,
                                const h3_gpu_tensor *input, uint32_t rows,
                                uint32_t columns) {
(void)gpu; (void)output; (void)scales; (void)input; (void)rows; (void)columns;
    return -1;
}

int h3_gpu_linear_int8_bf16(h3_gpu *gpu, h3_gpu_tensor *output,
                            h3_gpu_tensor *quantized_input,
                            h3_gpu_tensor *input_scales,
                            const h3_gpu_tensor *input,
                            const h3_gpu_tensor *weight,
                            const h3_gpu_tensor *weight_scales,
                            uint32_t rows, uint32_t input_dim,
                            uint32_t output_dim,
                            int use_slower_uncached_int8_scales) {
(void)gpu; (void)output; (void)quantized_input; (void)input_scales; (void)input; (void)weight; (void)weight_scales; (void)rows; (void)input_dim; (void)output_dim; (void)use_slower_uncached_int8_scales;
    return -1;
}

int h3_gpu_linear_int8_head_major_bf16(
                            h3_gpu *gpu, h3_gpu_tensor *output,
                            h3_gpu_tensor *quantized_input,
                            h3_gpu_tensor *input_scales,
                            const h3_gpu_tensor *input,
                            const h3_gpu_tensor *weight,
                            const h3_gpu_tensor *weight_scales,
                            uint32_t rows, uint32_t heads,
                            uint32_t head_dim, uint32_t output_dim) {
(void)gpu; (void)output; (void)quantized_input; (void)input_scales; (void)input; (void)weight; (void)weight_scales; (void)rows; (void)heads; (void)head_dim; (void)output_dim;
    return -1;
}

int h3_gpu_mlp_int8_bf16(h3_gpu *gpu, h3_gpu_tensor *output,
                         h3_gpu_tensor *activated,
                         h3_gpu_tensor *quantized_activation,
                         h3_gpu_tensor *activation_scales,
                         const h3_gpu_tensor *input,
                         const h3_gpu_tensor *fc1_weight,
                         const h3_gpu_tensor *fc1_scales,
                         const h3_gpu_tensor *fc2_weight,
                         const h3_gpu_tensor *fc2_scales,
                         const h3_gpu_tensor *fc1_bf16,
                         const h3_gpu_tensor *fc2_bf16, uint32_t rows,
                         uint32_t input_dim, uint32_t hidden_dim,
                         uint32_t output_dim,
                         int use_slower_grouped_quantizer,
                         int use_slower_dynamic_fc1_k,
                         int use_int8_row_fc2,
                         int input_is_quantized) {
(void)gpu; (void)output; (void)activated; (void)quantized_activation; (void)activation_scales; (void)input; (void)fc1_weight; (void)fc1_scales; (void)fc2_weight; (void)fc2_scales; (void)fc1_bf16; (void)fc2_bf16; (void)rows; (void)input_dim; (void)hidden_dim; (void)output_dim; (void)use_slower_grouped_quantizer; (void)use_slower_dynamic_fc1_k; (void)use_int8_row_fc2; (void)input_is_quantized;
    return -1;
}

int h3_gpu_silu_bf16(h3_gpu *gpu, h3_gpu_tensor *output,
                     const h3_gpu_tensor *input, uint32_t elements) {
(void)gpu; (void)output; (void)input; (void)elements;
    return -1;
}

int h3_gpu_rms_norm_bf16(h3_gpu *gpu, h3_gpu_tensor *output,
                         const h3_gpu_tensor *input,
                         const h3_gpu_tensor *weight, uint32_t rows,
                         uint32_t width, float epsilon) {
(void)gpu; (void)output; (void)input; (void)weight; (void)rows; (void)width; (void)epsilon;
    return -1;
}

int h3_gpu_layer_norm_bf16(h3_gpu *gpu, h3_gpu_tensor *output,
                           const h3_gpu_tensor *input,
                           const h3_gpu_tensor *weight,
                           const h3_gpu_tensor *bias, uint32_t rows,
                           uint32_t width, float epsilon) {
(void)gpu; (void)output; (void)input; (void)weight; (void)bias; (void)rows; (void)width; (void)epsilon;
    return -1;
}

int h3_gpu_gelu_bf16(h3_gpu *gpu, h3_gpu_tensor *output,
                     const h3_gpu_tensor *input, uint32_t elements,
                     int approximate) {
(void)gpu; (void)output; (void)input; (void)elements; (void)approximate;
    return -1;
}

int h3_gpu_vision_qkv_rope_bf16(
                     h3_gpu *gpu, h3_gpu_tensor *query,
                     h3_gpu_tensor *key, h3_gpu_tensor *value,
                     const h3_gpu_tensor *qkv,
                     const h3_gpu_tensor *rope_cos,
                     const h3_gpu_tensor *rope_sin, uint32_t sequence,
                     uint32_t heads, uint32_t head_dim,
                     uint32_t rope_half) {
(void)gpu; (void)query; (void)key; (void)value; (void)qkv; (void)rope_cos; (void)rope_sin; (void)sequence; (void)heads; (void)head_dim; (void)rope_half;
    return -1;
}

int h3_gpu_adaln_bf16(h3_gpu *gpu, h3_gpu_tensor *output,
                      const h3_gpu_tensor *input,
                      const h3_gpu_tensor *norm_weight,
                      const h3_gpu_tensor *modulation,
                      const h3_gpu_tensor *row_map, uint32_t rows,
                      uint32_t width, uint32_t slots, uint32_t shift_slot,
                      uint32_t scale_slot, float epsilon) {
(void)gpu; (void)output; (void)input; (void)norm_weight; (void)modulation; (void)row_map; (void)rows; (void)width; (void)slots; (void)shift_slot; (void)scale_slot; (void)epsilon;
    return -1;
}

int h3_gpu_adaln_bf16_offset(h3_gpu *gpu, h3_gpu_tensor *output,
                      const h3_gpu_tensor *input, size_t input_offset,
                      const h3_gpu_tensor *norm_weight,
                      const h3_gpu_tensor *modulation,
                      const h3_gpu_tensor *row_map, uint32_t rows,
                      uint32_t width, uint32_t slots, uint32_t shift_slot,
                      uint32_t scale_slot, float epsilon) {
(void)gpu; (void)output; (void)input; (void)input_offset; (void)norm_weight; (void)modulation; (void)row_map; (void)rows; (void)width; (void)slots; (void)shift_slot; (void)scale_slot; (void)epsilon;
    return -1;
}

int h3_gpu_adaln_linear_bf16(
                      h3_gpu *gpu, h3_gpu_tensor *output,
                      h3_gpu_tensor *inverse,
                      const h3_gpu_tensor *input, size_t input_offset,
                      const h3_gpu_tensor *norm_weight,
                      const h3_gpu_tensor *modulation,
                      const h3_gpu_tensor *row_map,
                      const h3_gpu_tensor *weight,
                      const h3_gpu_tensor *bias, uint32_t rows,
                      uint32_t width, uint32_t output_dim, uint32_t slots,
                      uint32_t shift_slot, uint32_t scale_slot,
                      float epsilon) {
(void)gpu; (void)output; (void)inverse; (void)input; (void)input_offset; (void)norm_weight; (void)modulation; (void)row_map; (void)weight; (void)bias; (void)rows; (void)width; (void)output_dim; (void)slots; (void)shift_slot; (void)scale_slot; (void)epsilon;
    return -1;
}

int h3_gpu_gate_bf16(h3_gpu *gpu, h3_gpu_tensor *output,
                     const h3_gpu_tensor *residual,
                     const h3_gpu_tensor *branch,
                     const h3_gpu_tensor *modulation,
                     const h3_gpu_tensor *row_map, uint32_t rows,
                     uint32_t width, uint32_t slots, uint32_t gate_slot) {
(void)gpu; (void)output; (void)residual; (void)branch; (void)modulation; (void)row_map; (void)rows; (void)width; (void)slots; (void)gate_slot;
    return -1;
}

int h3_gpu_gate_adaln_bf16(
                     h3_gpu *gpu, h3_gpu_tensor *gated_residual,
                     h3_gpu_tensor *output,
                     const h3_gpu_tensor *residual,
                     const h3_gpu_tensor *branch,
                     const h3_gpu_tensor *norm_weight,
                     const h3_gpu_tensor *gate_modulation,
                     const h3_gpu_tensor *norm_modulation,
                     const h3_gpu_tensor *row_map, uint32_t rows,
                     uint32_t width, uint32_t slots, uint32_t gate_slot,
                     uint32_t shift_slot, uint32_t scale_slot,
                     float epsilon) {
(void)gpu; (void)gated_residual; (void)output; (void)residual; (void)branch; (void)norm_weight; (void)gate_modulation; (void)norm_modulation; (void)row_map; (void)rows; (void)width; (void)slots; (void)gate_slot; (void)shift_slot; (void)scale_slot; (void)epsilon;
    return -1;
}

int h3_gpu_gate_adaln_quantize_int8(
                     h3_gpu *gpu, h3_gpu_tensor *gated_residual,
                     h3_gpu_tensor *quantized_output,
                     h3_gpu_tensor *quantized_scales,
                     const h3_gpu_tensor *residual,
                     const h3_gpu_tensor *branch,
                     const h3_gpu_tensor *norm_weight,
                     const h3_gpu_tensor *gate_modulation,
                     const h3_gpu_tensor *norm_modulation,
                     const h3_gpu_tensor *row_map, uint32_t rows,
                     uint32_t padded_rows, uint32_t width, uint32_t slots,
                     uint32_t gate_slot, uint32_t shift_slot,
                     uint32_t scale_slot, float epsilon) {
(void)gpu; (void)gated_residual; (void)quantized_output; (void)quantized_scales; (void)residual; (void)branch; (void)norm_weight; (void)gate_modulation; (void)norm_modulation; (void)row_map; (void)rows; (void)padded_rows; (void)width; (void)slots; (void)gate_slot; (void)shift_slot; (void)scale_slot; (void)epsilon;
    return -1;
}

int h3_gpu_qkv_rope_bf16(h3_gpu *gpu, h3_gpu_tensor *query,
                         h3_gpu_tensor *key, h3_gpu_tensor *value,
                         const h3_gpu_tensor *qkv,
                         const h3_gpu_tensor *q_norm,
                         const h3_gpu_tensor *k_norm,
                         const h3_gpu_tensor *rope_cos,
                         const h3_gpu_tensor *rope_sin, uint32_t sequence,
                         uint32_t heads, uint32_t head_dim,
                         uint32_t rope_half, float epsilon) {
(void)gpu; (void)query; (void)key; (void)value; (void)qkv; (void)q_norm; (void)k_norm; (void)rope_cos; (void)rope_sin; (void)sequence; (void)heads; (void)head_dim; (void)rope_half; (void)epsilon;
    return -1;
}

int h3_gpu_grouped_qkv_rope_bf16(h3_gpu *gpu, h3_gpu_tensor *query,
                                 h3_gpu_tensor *key, h3_gpu_tensor *value,
                                 const h3_gpu_tensor *qkv,
                                 const h3_gpu_tensor *q_norm,
                                 const h3_gpu_tensor *k_norm,
                                 const h3_gpu_tensor *rope_cos,
                                 const h3_gpu_tensor *rope_sin,
                                 uint32_t sequence, uint32_t heads,
                                 uint32_t head_dim, uint32_t rope_half,
                                 float epsilon) {
(void)gpu; (void)query; (void)key; (void)value; (void)qkv; (void)q_norm; (void)k_norm; (void)rope_cos; (void)rope_sin; (void)sequence; (void)heads; (void)head_dim; (void)rope_half; (void)epsilon;
    return -1;
}

int h3_gpu_grouped_qkv_linear_rope_bf16(
                                 h3_gpu *gpu,
                                 h3_gpu_tensor *query,
                                 h3_gpu_tensor *key,
                                 h3_gpu_tensor *value,
                                 h3_gpu_tensor *qkv,
                                 const h3_gpu_tensor *input,
                                 const h3_gpu_tensor *weight,
                                 const h3_gpu_tensor *q_norm,
                                 const h3_gpu_tensor *k_norm,
                                 const h3_gpu_tensor *rope_cos,
                                 const h3_gpu_tensor *rope_sin,
                                 uint32_t rows, uint32_t input_dim,
                                 uint32_t heads, uint32_t head_dim,
                                 uint32_t rope_half, float epsilon) {
(void)gpu; (void)query; (void)key; (void)value; (void)qkv; (void)input; (void)weight; (void)q_norm; (void)k_norm; (void)rope_cos; (void)rope_sin; (void)rows; (void)input_dim; (void)heads; (void)head_dim; (void)rope_half; (void)epsilon;
    return -1;
}

int h3_gpu_grouped_qkv_linear_rope_int8(
                                 h3_gpu *gpu,
                                 h3_gpu_tensor *query,
                                 h3_gpu_tensor *key,
                                 h3_gpu_tensor *value,
                                 h3_gpu_tensor *qkv_scratch,
                                 h3_gpu_tensor *quantized_input,
                                 h3_gpu_tensor *input_scales,
                                 const h3_gpu_tensor *input,
                                 const h3_gpu_tensor *weight,
                                 const h3_gpu_tensor *weight_scales,
                                 const h3_gpu_tensor *q_norm,
                                 const h3_gpu_tensor *k_norm,
                                 const h3_gpu_tensor *rope_cos,
                                 const h3_gpu_tensor *rope_sin,
                                 uint32_t rows, uint32_t input_dim,
                                 uint32_t heads, uint32_t head_dim,
                                 uint32_t rope_half, float epsilon,
                                 int input_is_quantized,
                                 int use_slower_unfused_qkv_rope,
                                 int use_slower_scalar_qkv_rms,
                                 int use_slower_uncached_int8_scales) {
(void)gpu; (void)query; (void)key; (void)value; (void)qkv_scratch; (void)quantized_input; (void)input_scales; (void)input; (void)weight; (void)weight_scales; (void)q_norm; (void)k_norm; (void)rope_cos; (void)rope_sin; (void)rows; (void)input_dim; (void)heads; (void)head_dim; (void)rope_half; (void)epsilon; (void)input_is_quantized; (void)use_slower_unfused_qkv_rope; (void)use_slower_scalar_qkv_rms; (void)use_slower_uncached_int8_scales;
    return -1;
}

int h3_gpu_sdpa_bf16(h3_gpu *gpu, h3_gpu_tensor *output,
                     const h3_gpu_tensor *query, const h3_gpu_tensor *key,
                     const h3_gpu_tensor *value, uint32_t sequence,
                     uint32_t heads, uint32_t head_dim, float scale) {
(void)gpu; (void)output; (void)query; (void)key; (void)value; (void)sequence; (void)heads; (void)head_dim; (void)scale;
    return -1;
}

int h3_gpu_sdpa_bf16_head_major_output(
                     h3_gpu *gpu, h3_gpu_tensor *output,
                     const h3_gpu_tensor *query, const h3_gpu_tensor *key,
                     const h3_gpu_tensor *value, uint32_t sequence,
                     uint32_t heads, uint32_t head_dim, float scale) {
(void)gpu; (void)output; (void)query; (void)key; (void)value; (void)sequence; (void)heads; (void)head_dim; (void)scale;
    return -1;
}

int h3_gpu_swiglu_bf16(h3_gpu *gpu, h3_gpu_tensor *output,
                       const h3_gpu_tensor *fused, uint32_t rows,
                       uint32_t width) {
(void)gpu; (void)output; (void)fused; (void)rows; (void)width;
    return -1;
}

int h3_gpu_embedding_bf16(h3_gpu *gpu, h3_gpu_tensor *output,
                          const h3_gpu_tensor *weight,
                          const h3_gpu_tensor *token_ids, uint32_t tokens,
                          uint32_t vocab_size, uint32_t width) {
(void)gpu; (void)output; (void)weight; (void)token_ids; (void)tokens; (void)vocab_size; (void)width;
    return -1;
}

int h3_gpu_text_qk_rope_bf16(h3_gpu *gpu,
                             h3_gpu_tensor *query_output,
                             h3_gpu_tensor *key_output,
                             const h3_gpu_tensor *query_input,
                             const h3_gpu_tensor *key_input,
                             const h3_gpu_tensor *q_norm,
                             const h3_gpu_tensor *k_norm,
                             const h3_gpu_tensor *rope_cos,
                             const h3_gpu_tensor *rope_sin,
                             uint32_t sequence, uint32_t query_heads,
                             uint32_t kv_heads, uint32_t head_dim,
                             float epsilon) {
(void)gpu; (void)query_output; (void)key_output; (void)query_input; (void)key_input; (void)q_norm; (void)k_norm; (void)rope_cos; (void)rope_sin; (void)sequence; (void)query_heads; (void)kv_heads; (void)head_dim; (void)epsilon;
    return -1;
}

int h3_gpu_head_rms_norm_bf16(h3_gpu *gpu, h3_gpu_tensor *tensor,
                              const h3_gpu_tensor *weight,
                              uint32_t sequence, uint32_t heads,
                              uint32_t head_dim, float epsilon) {
(void)gpu; (void)tensor; (void)weight; (void)sequence; (void)heads; (void)head_dim; (void)epsilon;
    return -1;
}

int h3_gpu_rope_text_bf16(h3_gpu *gpu, h3_gpu_tensor *query,
                          h3_gpu_tensor *key,
                          const h3_gpu_tensor *rope_cos_f32,
                          const h3_gpu_tensor *rope_sin_f32,
                          uint32_t sequence, uint32_t query_heads,
                          uint32_t kv_heads, uint32_t head_dim) {
(void)gpu; (void)query; (void)key; (void)rope_cos_f32; (void)rope_sin_f32; (void)sequence; (void)query_heads; (void)kv_heads; (void)head_dim;
    return -1;
}

int h3_gpu_gqa_causal_bf16(h3_gpu *gpu, h3_gpu_tensor *output,
                           const h3_gpu_tensor *query,
                           const h3_gpu_tensor *key,
                           const h3_gpu_tensor *value,
                           uint32_t sequence, uint32_t query_heads,
                           uint32_t kv_heads, uint32_t head_dim,
                           float scale) {
(void)gpu; (void)output; (void)query; (void)key; (void)value; (void)sequence; (void)query_heads; (void)kv_heads; (void)head_dim; (void)scale;
    return -1;
}

int h3_gpu_add_bf16(h3_gpu *gpu, h3_gpu_tensor *output,
                    const h3_gpu_tensor *left, const h3_gpu_tensor *right,
                    uint32_t elements) {
(void)gpu; (void)output; (void)left; (void)right; (void)elements;
    return -1;
}

int h3_gpu_sub_bf16(h3_gpu *gpu, h3_gpu_tensor *output,
                    const h3_gpu_tensor *left, const h3_gpu_tensor *right,
                    uint32_t elements) {
(void)gpu; (void)output; (void)left; (void)right; (void)elements;
    return -1;
}

int h3_gpu_token_pool_bf16(h3_gpu *gpu, h3_gpu_tensor *output,
                           const h3_gpu_tensor *input,
                           size_t input_offset,
                           h3_gpu_tensor *original,
                           size_t original_offset,
                           h3_gpu_tensor *baseline,
                           size_t baseline_offset,
                           const h3_gpu_tensor *baseline_indices,
                           const h3_gpu_tensor *pairs, uint32_t input_rows,
                           uint32_t rows, uint32_t baseline_rows,
                           uint32_t width) {
(void)gpu; (void)output; (void)input; (void)input_offset; (void)original; (void)original_offset; (void)baseline; (void)baseline_offset; (void)baseline_indices; (void)pairs; (void)input_rows; (void)rows; (void)baseline_rows; (void)width;
    return -1;
}

int h3_gpu_token_pool_adaln_bf16(
                           h3_gpu *gpu, h3_gpu_tensor *residual,
                           h3_gpu_tensor *output,
                           const h3_gpu_tensor *input, size_t input_offset,
                           h3_gpu_tensor *original, size_t original_offset,
                           h3_gpu_tensor *baseline, size_t baseline_offset,
                           const h3_gpu_tensor *baseline_indices,
                           const h3_gpu_tensor *pairs,
                           const h3_gpu_tensor *norm_weight,
                           const h3_gpu_tensor *modulation,
                           const h3_gpu_tensor *row_map,
                           uint32_t input_rows, uint32_t rows,
                           uint32_t baseline_rows, uint32_t width,
                           uint32_t slots, uint32_t shift_slot,
                           uint32_t scale_slot, float epsilon) {
(void)gpu; (void)residual; (void)output; (void)input; (void)input_offset; (void)original; (void)original_offset; (void)baseline; (void)baseline_offset; (void)baseline_indices; (void)pairs; (void)norm_weight; (void)modulation; (void)row_map; (void)input_rows; (void)rows; (void)baseline_rows; (void)width; (void)slots; (void)shift_slot; (void)scale_slot; (void)epsilon;
    return -1;
}

int h3_gpu_token_expand_delta_bf16(
                           h3_gpu *gpu, h3_gpu_tensor *output,
                           const h3_gpu_tensor *original,
                           size_t original_offset,
                           const h3_gpu_tensor *reduced,
                           const h3_gpu_tensor *baseline,
                           size_t baseline_offset,
                           const h3_gpu_tensor *baseline_indices,
                           const h3_gpu_tensor *parents, uint32_t rows,
                           uint32_t reduced_rows, uint32_t baseline_rows,
                           uint32_t width,
                           uint32_t exact_prefix_rows,
                           float update_scale) {
(void)gpu; (void)output; (void)original; (void)original_offset; (void)reduced; (void)baseline; (void)baseline_offset; (void)baseline_indices; (void)parents; (void)rows; (void)reduced_rows; (void)baseline_rows; (void)width; (void)exact_prefix_rows; (void)update_scale;
    return -1;
}

int h3_gpu_token_expand_adaln_bf16(
                           h3_gpu *gpu, h3_gpu_tensor *residual,
                           h3_gpu_tensor *output,
                           const h3_gpu_tensor *original,
                           size_t original_offset,
                           const h3_gpu_tensor *reduced,
                           const h3_gpu_tensor *baseline,
                           size_t baseline_offset,
                           const h3_gpu_tensor *baseline_indices,
                           const h3_gpu_tensor *parents,
                           const h3_gpu_tensor *norm_weight,
                           const h3_gpu_tensor *modulation,
                           const h3_gpu_tensor *row_map,
                           uint32_t rows, uint32_t reduced_rows,
                           uint32_t baseline_rows, uint32_t width,
                           uint32_t exact_prefix_rows, float update_scale,
                           uint32_t slots, uint32_t shift_slot,
                           uint32_t scale_slot, float epsilon) {
(void)gpu; (void)residual; (void)output; (void)original; (void)original_offset; (void)reduced; (void)baseline; (void)baseline_offset; (void)baseline_indices; (void)parents; (void)norm_weight; (void)modulation; (void)row_map; (void)rows; (void)reduced_rows; (void)baseline_rows; (void)width; (void)exact_prefix_rows; (void)update_scale; (void)slots; (void)shift_slot; (void)scale_slot; (void)epsilon;
    return -1;
}

int h3_gpu_euler_bf16(h3_gpu *gpu, h3_gpu_tensor *sample,
                      size_t sample_offset, const h3_gpu_tensor *last,
                      const h3_gpu_tensor *previous, uint32_t elements,
                      float delta, float ratio) {
(void)gpu; (void)sample; (void)sample_offset; (void)last; (void)previous; (void)elements; (void)delta; (void)ratio;
    return -1;
}

int h3_gpu_silu_mul_bf16(h3_gpu *gpu, h3_gpu_tensor *output,
                         const h3_gpu_tensor *gate,
                         const h3_gpu_tensor *up, uint32_t elements) {
(void)gpu; (void)output; (void)gate; (void)up; (void)elements;
    return -1;
}

