#!/usr/bin/env python3
"""Generate the CUDA correctness kernels from the Vulkan GLSL oracle.

The Vulkan source deliberately uses a small, C-like GLSL subset.  Keeping this
translator in-tree lets both Linux backends share arithmetic order while CUDA
can replace hot kernels with specialized implementations behind the same
launcher later.
"""

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent
GLSL = ROOT / "h3_vulkan_shaders.comp"
VULKAN_C = ROOT / "h3_gpu_vulkan.c"
OUTPUT = ROOT / "h3_cuda_kernels.cu"

source = GLSL.read_text()
backend = VULKAN_C.read_text()

buffer_re = re.compile(
    r"layout\(set\s*=\s*0,\s*binding\s*=\s*(\d+)\)\s*"
    r"(?:(?:readonly|writeonly)\s+)?buffer\s+\w+\s*"
    r"\{\s*(\w+)\s+data\[\];\s*\}\s*(\w+)\s*;"
)
type_map = {"uint": "uint32_t", "uvec2": "uint2"}
buffers = {
    name: (int(binding), type_map.get(element_type, element_type))
    for binding, element_type, name in buffer_re.findall(source)
    if name != "args"
}

shared_re = re.compile(
    r"^shared\s+(\w+)\s+(\w+)((?:\[[0-9]+\])*)\s*;", re.MULTILINE
)
shared = {
    name: (type_map.get(element_type, element_type), dimensions)
    for element_type, name, dimensions in shared_re.findall(source)
}

names_block = re.search(
    r"h3_vk_kernel_names\[H3_VK_KERNEL_COUNT\]\s*=\s*\{(.*?)\};",
    backend,
    re.DOTALL,
)
layout_block = re.search(
    r"h3_vk_kernel_layout\[H3_VK_KERNEL_COUNT\]\s*=\s*\{(.*?)\};",
    backend,
    re.DOTALL,
)
if not names_block or not layout_block:
    raise SystemExit("cannot parse Vulkan kernel tables")
names = re.findall(r'"(main_[^"]+)"', names_block.group(1))
layouts = [int(value) for value in re.findall(r"\b[012]\b", layout_block.group(1))]
if len(names) != len(layouts):
    raise SystemExit(f"kernel table mismatch: {len(names)} names, {len(layouts)} layouts")


def function_body(name: str) -> str:
    marker = f"void {name}()"
    start = source.find(marker)
    if start < 0:
        raise SystemExit(f"missing GLSL function {name}")
    opening = source.find("{", start + len(marker))
    depth = 0
    for index in range(opening, len(source)):
        if source[index] == "{":
            depth += 1
        elif source[index] == "}":
            depth -= 1
            if depth == 0:
                return source[opening + 1:index]
    raise SystemExit(f"unterminated GLSL function {name}")


def convert_body(name: str) -> str:
    body = function_body(name)
    used_buffers = sorted(
        (alias, binding, element_type)
        for alias, (binding, element_type) in buffers.items()
        if re.search(rf"\b{re.escape(alias)}\.data\b", body)
    )
    used_shared = sorted(
        (shared_name, element_type, dimensions)
        for shared_name, (element_type, dimensions) in shared.items()
        if re.search(rf"\b{re.escape(shared_name)}\b", body)
    )

    body = body.replace("args.data.", "args.")
    for alias, _, _ in used_buffers:
        body = re.sub(rf"\b{re.escape(alias)}\.data\b", alias, body)

    replacements = {
        "gl_GlobalInvocationID.x": "(blockIdx.x * blockDim.x + threadIdx.x)",
        "gl_GlobalInvocationID.y": "(blockIdx.y * blockDim.y + threadIdx.y)",
        "gl_GlobalInvocationID.z": "(blockIdx.z * blockDim.z + threadIdx.z)",
        "gl_WorkGroupID.x": "blockIdx.x",
        "gl_WorkGroupID.y": "blockIdx.y",
        "gl_WorkGroupID.z": "blockIdx.z",
        "gl_LocalInvocationID.x": "threadIdx.x",
        "gl_LocalInvocationID.y": "threadIdx.y",
        "gl_LocalInvocationID.z": "threadIdx.z",
        "barrier()": "__syncthreads()",
        "roundEven(": "rintf(",
        "inversesqrt(": "h3_rsqrt(",
        "clamp(": "h3_clamp(",
        "max(": "h3_max(",
        "abs(": "fabsf(",
        "fma(": "fmaf(",
        "exp(": "expf(",
        "tanh(": "tanhf(",
        "sin(": "sinf(",
    }
    for old, new in replacements.items():
        body = body.replace(old, new)
    # The GLSL conv3d entry computes y from the flattened z plane; its direct
    # global-y value is intentionally unused.
    if name == "main_conv3d_f32":
        body = re.sub(r"\s*uint out_y = .*?;\n", "\n", body, count=1)

    declarations = []
    for alias, binding, element_type in used_buffers:
        declarations.append(
            f"    {element_type} *{alias} = static_cast<{element_type} *>(b{binding});"
        )
    for shared_name, element_type, dimensions in used_shared:
        declarations.append(
            f"    __shared__ {element_type} {shared_name}{dimensions};"
        )
    prefix = "\n".join(declarations)
    if prefix:
        prefix += "\n"
    parameters = ", ".join(f"void *b{i}" for i in range(10))
    return (
        f"__global__ void {name}(h3_cuda_args args, {parameters}) {{\n"
        f"{prefix}{body}\n}}\n"
    )

preamble = r'''/* Generated by scripts/generate_cuda_kernels.py.
 * Source arithmetic oracle: h3_vulkan_shaders.comp.
 * Do not edit this file directly; specialized hot kernels may be added to
 * the generator or selected separately by h3_cuda_launch(). */
#include "h3_cuda_kernels.h"

#include <cuda_runtime.h>
#include <math.h>
#include <stdint.h>
#include <stdio.h>

using uvec2 = uint2;

__device__ __forceinline__ float h3_bf16_to_f32(uint16_t value) {
    return __uint_as_float(static_cast<uint32_t>(value) << 16);
}

__device__ __forceinline__ uint32_t h3_f32_to_bf16(float value) {
    uint32_t bits = __float_as_uint(value);
    bits += 0x7fffu + ((bits >> 16) & 1u);
    return bits >> 16;
}

#define H3_BF16_TO_F32(value) h3_bf16_to_f32(value)

__device__ __forceinline__ float h3_rsqrt(float value) {
    return 1.0f / sqrtf(value);
}

template <typename T>
__device__ __forceinline__ T h3_max(T left, T right) {
    return left > right ? left : right;
}

template <typename T>
__device__ __forceinline__ T h3_clamp(T value, T minimum, T maximum) {
    return value < minimum ? minimum : (value > maximum ? maximum : value);
}
'''

parts = [preamble]
for name in names:
    parts.append(convert_body(name))

launcher = [r'''
extern "C" int h3_cuda_launch(h3_cuda_kernel kernel, void *stream_handle,
                              const h3_cuda_args *args,
                              void *const buffers[10], uint32_t groups_x,
                              uint32_t groups_y, uint32_t groups_z,
                              char *error, size_t error_size) {
    if (!args || !buffers) {
        if (error && error_size)
            snprintf(error, error_size, "invalid CUDA launch arguments");
        return 0;
    }
    dim3 grid(groups_x ? groups_x : 1u, groups_y ? groups_y : 1u,
              groups_z ? groups_z : 1u);
    cudaStream_t stream = static_cast<cudaStream_t>(stream_handle);
    void *b0 = buffers[0];
    void *b1 = buffers[1];
    void *b2 = buffers[2];
    void *b3 = buffers[3];
    void *b4 = buffers[4];
    void *b5 = buffers[5];
    void *b6 = buffers[6];
    void *b7 = buffers[7];
    void *b8 = buffers[8];
    void *b9 = buffers[9];
    switch (kernel) {
''']
for index, (name, layout) in enumerate(zip(names, layouts)):
    if layout == 1:
        block = "dim3(16u, 16u, 1u)"
    elif layout == 2:
        block = "dim3(128u, 1u, 1u)"
    else:
        block = "dim3(256u, 1u, 1u)"
    enum_name = "H3_CUDA_KERNEL_" + name.removeprefix("main_").upper()
    launcher.append(
        f"        case {enum_name}:\n"
        f"            {name}<<<grid, {block}, 0, stream>>>(*args, b0, b1, b2, b3, b4, b5, b6, b7, b8, b9);\n"
        f"            break;\n"
    )
launcher.append(r'''        case H3_CUDA_KERNEL_COUNT:
        default:
            if (error && error_size)
                snprintf(error, error_size, "invalid CUDA kernel id %d",
                         static_cast<int>(kernel));
            return 0;
    }
    cudaError_t result = cudaGetLastError();
    if (result != cudaSuccess) {
        if (error && error_size)
            snprintf(error, error_size, "CUDA kernel launch failed: %s",
                     cudaGetErrorString(result));
        return 0;
    }
    return 1;
}
''')
parts.extend(launcher)
OUTPUT.write_text("\n".join(parts))
print(f"generated {OUTPUT.relative_to(ROOT)}: {len(names)} kernels")
